version: '3.9'
services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      # Mount the current directory to /app in the container
    volumes:
        - .:/app
        - /app/node_modules

    # Specify the command to run when the container starts
    command: npm run dev
